backend:
  name: github
  branch: master
  repo: PhucBuiDinh/blog
  base_url: https://45qsx9luhe.execute-api.us-east-1.amazonaws.com
  auth_endpoint: /prod/auth
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

locale: 'ja'
local_backend: true
publish_mode: editorial_workflow

media_folder: public/images 
public_folder: /images
